# Generated by Django 5.0.6 on 2025-08-12 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustlehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_user_email',
            field=models.EmailField(blank=True, help_text='Email of the user being referred', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
